name: Build Doxygen documentation Action

on:
  push:
    branches: [ main ]
    paths:
      - '**.cpp'
      - '**.hpp'
      - '.github/workflows/doxygen.yml'
      - 'docs/Doxyfile'
      - 'CMakeLists.txt'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  doxygen:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Doxygen Action
        uses: mattnotmitt/doxygen-action@v1.12
        with:
          working-directory: "./docs"
          doxyfile-path: "./Doxyfile"
          enable-latex: true

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/doc/html
